name: Security vulnerability scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * SUN'

jobs:
  call-shared-security-vulnerabiliies-deep-scan:
    uses: cgi-no-utility/github-shared-workflows/.github/workflows/maven-security-vulnerability-deep-scan.yml@main
